package project.impl;

import project.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultBar_on_road <br>
 * @version generated on Sat Sep 18 09:05:47 CEST 2021 by barto
 */
public class DefaultBar_on_road extends WrappedIndividualImpl implements Bar_on_road {

    public DefaultBar_on_road(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
