package project.impl;

import project.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultTrash <br>
 * @version generated on Thu Sep 16 00:32:04 CEST 2021 by barto
 */
public class DefaultTrash extends WrappedIndividualImpl implements Trash {

    public DefaultTrash(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
