package project.impl;

import project.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultState_change <br>
 * @version generated on Sat Sep 18 09:05:51 CEST 2021 by barto
 */
public class DefaultState_change extends WrappedIndividualImpl implements State_change {

    public DefaultState_change(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
